/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardDashboardRouteRouteImport } from './routes/_dashboard/dashboard/route'
import { Route as DashboardDashboardIndexRouteImport } from './routes/_dashboard/dashboard/index'
import { Route as DashboardDashboardTenantsIndexRouteImport } from './routes/_dashboard/dashboard/tenants/index'
import { Route as DashboardDashboardRoomsIndexRouteImport } from './routes/_dashboard/dashboard/rooms/index'
import { Route as DashboardDashboardReportsIndexRouteImport } from './routes/_dashboard/dashboard/reports/index'
import { Route as DashboardDashboardPropertiesIndexRouteImport } from './routes/_dashboard/dashboard/properties/index'
import { Route as DashboardDashboardProfileIndexRouteImport } from './routes/_dashboard/dashboard/profile/index'
import { Route as DashboardDashboardPaymentsIndexRouteImport } from './routes/_dashboard/dashboard/payments/index'
import { Route as DashboardDashboardPropertiesPropertyIdIndexRouteImport } from './routes/_dashboard/dashboard/properties/$propertyId/index'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDashboardRouteRoute = DashboardDashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDashboardIndexRoute = DashboardDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardDashboardRouteRoute,
} as any)
const DashboardDashboardTenantsIndexRoute =
  DashboardDashboardTenantsIndexRouteImport.update({
    id: '/tenants/',
    path: '/tenants/',
    getParentRoute: () => DashboardDashboardRouteRoute,
  } as any)
const DashboardDashboardRoomsIndexRoute =
  DashboardDashboardRoomsIndexRouteImport.update({
    id: '/rooms/',
    path: '/rooms/',
    getParentRoute: () => DashboardDashboardRouteRoute,
  } as any)
const DashboardDashboardReportsIndexRoute =
  DashboardDashboardReportsIndexRouteImport.update({
    id: '/reports/',
    path: '/reports/',
    getParentRoute: () => DashboardDashboardRouteRoute,
  } as any)
const DashboardDashboardPropertiesIndexRoute =
  DashboardDashboardPropertiesIndexRouteImport.update({
    id: '/properties/',
    path: '/properties/',
    getParentRoute: () => DashboardDashboardRouteRoute,
  } as any)
const DashboardDashboardProfileIndexRoute =
  DashboardDashboardProfileIndexRouteImport.update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => DashboardDashboardRouteRoute,
  } as any)
const DashboardDashboardPaymentsIndexRoute =
  DashboardDashboardPaymentsIndexRouteImport.update({
    id: '/payments/',
    path: '/payments/',
    getParentRoute: () => DashboardDashboardRouteRoute,
  } as any)
const DashboardDashboardPropertiesPropertyIdIndexRoute =
  DashboardDashboardPropertiesPropertyIdIndexRouteImport.update({
    id: '/properties/$propertyId/',
    path: '/properties/$propertyId/',
    getParentRoute: () => DashboardDashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof DashboardDashboardRouteRouteWithChildren
  '/dashboard/': typeof DashboardDashboardIndexRoute
  '/dashboard/payments/': typeof DashboardDashboardPaymentsIndexRoute
  '/dashboard/profile/': typeof DashboardDashboardProfileIndexRoute
  '/dashboard/properties/': typeof DashboardDashboardPropertiesIndexRoute
  '/dashboard/reports/': typeof DashboardDashboardReportsIndexRoute
  '/dashboard/rooms/': typeof DashboardDashboardRoomsIndexRoute
  '/dashboard/tenants/': typeof DashboardDashboardTenantsIndexRoute
  '/dashboard/properties/$propertyId/': typeof DashboardDashboardPropertiesPropertyIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof DashboardDashboardIndexRoute
  '/dashboard/payments': typeof DashboardDashboardPaymentsIndexRoute
  '/dashboard/profile': typeof DashboardDashboardProfileIndexRoute
  '/dashboard/properties': typeof DashboardDashboardPropertiesIndexRoute
  '/dashboard/reports': typeof DashboardDashboardReportsIndexRoute
  '/dashboard/rooms': typeof DashboardDashboardRoomsIndexRoute
  '/dashboard/tenants': typeof DashboardDashboardTenantsIndexRoute
  '/dashboard/properties/$propertyId': typeof DashboardDashboardPropertiesPropertyIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_dashboard/dashboard': typeof DashboardDashboardRouteRouteWithChildren
  '/_dashboard/dashboard/': typeof DashboardDashboardIndexRoute
  '/_dashboard/dashboard/payments/': typeof DashboardDashboardPaymentsIndexRoute
  '/_dashboard/dashboard/profile/': typeof DashboardDashboardProfileIndexRoute
  '/_dashboard/dashboard/properties/': typeof DashboardDashboardPropertiesIndexRoute
  '/_dashboard/dashboard/reports/': typeof DashboardDashboardReportsIndexRoute
  '/_dashboard/dashboard/rooms/': typeof DashboardDashboardRoomsIndexRoute
  '/_dashboard/dashboard/tenants/': typeof DashboardDashboardTenantsIndexRoute
  '/_dashboard/dashboard/properties/$propertyId/': typeof DashboardDashboardPropertiesPropertyIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/dashboard/'
    | '/dashboard/payments/'
    | '/dashboard/profile/'
    | '/dashboard/properties/'
    | '/dashboard/reports/'
    | '/dashboard/rooms/'
    | '/dashboard/tenants/'
    | '/dashboard/properties/$propertyId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/dashboard/payments'
    | '/dashboard/profile'
    | '/dashboard/properties'
    | '/dashboard/reports'
    | '/dashboard/rooms'
    | '/dashboard/tenants'
    | '/dashboard/properties/$propertyId'
  id:
    | '__root__'
    | '/'
    | '/_dashboard'
    | '/login'
    | '/register'
    | '/_dashboard/dashboard'
    | '/_dashboard/dashboard/'
    | '/_dashboard/dashboard/payments/'
    | '/_dashboard/dashboard/profile/'
    | '/_dashboard/dashboard/properties/'
    | '/_dashboard/dashboard/reports/'
    | '/_dashboard/dashboard/rooms/'
    | '/_dashboard/dashboard/tenants/'
    | '/_dashboard/dashboard/properties/$propertyId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/dashboard': {
      id: '/_dashboard/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardDashboardRouteRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard/': {
      id: '/_dashboard/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardDashboardIndexRouteImport
      parentRoute: typeof DashboardDashboardRouteRoute
    }
    '/_dashboard/dashboard/tenants/': {
      id: '/_dashboard/dashboard/tenants/'
      path: '/tenants'
      fullPath: '/dashboard/tenants/'
      preLoaderRoute: typeof DashboardDashboardTenantsIndexRouteImport
      parentRoute: typeof DashboardDashboardRouteRoute
    }
    '/_dashboard/dashboard/rooms/': {
      id: '/_dashboard/dashboard/rooms/'
      path: '/rooms'
      fullPath: '/dashboard/rooms/'
      preLoaderRoute: typeof DashboardDashboardRoomsIndexRouteImport
      parentRoute: typeof DashboardDashboardRouteRoute
    }
    '/_dashboard/dashboard/reports/': {
      id: '/_dashboard/dashboard/reports/'
      path: '/reports'
      fullPath: '/dashboard/reports/'
      preLoaderRoute: typeof DashboardDashboardReportsIndexRouteImport
      parentRoute: typeof DashboardDashboardRouteRoute
    }
    '/_dashboard/dashboard/properties/': {
      id: '/_dashboard/dashboard/properties/'
      path: '/properties'
      fullPath: '/dashboard/properties/'
      preLoaderRoute: typeof DashboardDashboardPropertiesIndexRouteImport
      parentRoute: typeof DashboardDashboardRouteRoute
    }
    '/_dashboard/dashboard/profile/': {
      id: '/_dashboard/dashboard/profile/'
      path: '/profile'
      fullPath: '/dashboard/profile/'
      preLoaderRoute: typeof DashboardDashboardProfileIndexRouteImport
      parentRoute: typeof DashboardDashboardRouteRoute
    }
    '/_dashboard/dashboard/payments/': {
      id: '/_dashboard/dashboard/payments/'
      path: '/payments'
      fullPath: '/dashboard/payments/'
      preLoaderRoute: typeof DashboardDashboardPaymentsIndexRouteImport
      parentRoute: typeof DashboardDashboardRouteRoute
    }
    '/_dashboard/dashboard/properties/$propertyId/': {
      id: '/_dashboard/dashboard/properties/$propertyId/'
      path: '/properties/$propertyId'
      fullPath: '/dashboard/properties/$propertyId/'
      preLoaderRoute: typeof DashboardDashboardPropertiesPropertyIdIndexRouteImport
      parentRoute: typeof DashboardDashboardRouteRoute
    }
  }
}

interface DashboardDashboardRouteRouteChildren {
  DashboardDashboardIndexRoute: typeof DashboardDashboardIndexRoute
  DashboardDashboardPaymentsIndexRoute: typeof DashboardDashboardPaymentsIndexRoute
  DashboardDashboardProfileIndexRoute: typeof DashboardDashboardProfileIndexRoute
  DashboardDashboardPropertiesIndexRoute: typeof DashboardDashboardPropertiesIndexRoute
  DashboardDashboardReportsIndexRoute: typeof DashboardDashboardReportsIndexRoute
  DashboardDashboardRoomsIndexRoute: typeof DashboardDashboardRoomsIndexRoute
  DashboardDashboardTenantsIndexRoute: typeof DashboardDashboardTenantsIndexRoute
  DashboardDashboardPropertiesPropertyIdIndexRoute: typeof DashboardDashboardPropertiesPropertyIdIndexRoute
}

const DashboardDashboardRouteRouteChildren: DashboardDashboardRouteRouteChildren =
  {
    DashboardDashboardIndexRoute: DashboardDashboardIndexRoute,
    DashboardDashboardPaymentsIndexRoute: DashboardDashboardPaymentsIndexRoute,
    DashboardDashboardProfileIndexRoute: DashboardDashboardProfileIndexRoute,
    DashboardDashboardPropertiesIndexRoute:
      DashboardDashboardPropertiesIndexRoute,
    DashboardDashboardReportsIndexRoute: DashboardDashboardReportsIndexRoute,
    DashboardDashboardRoomsIndexRoute: DashboardDashboardRoomsIndexRoute,
    DashboardDashboardTenantsIndexRoute: DashboardDashboardTenantsIndexRoute,
    DashboardDashboardPropertiesPropertyIdIndexRoute:
      DashboardDashboardPropertiesPropertyIdIndexRoute,
  }

const DashboardDashboardRouteRouteWithChildren =
  DashboardDashboardRouteRoute._addFileChildren(
    DashboardDashboardRouteRouteChildren,
  )

interface DashboardRouteChildren {
  DashboardDashboardRouteRoute: typeof DashboardDashboardRouteRouteWithChildren
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardDashboardRouteRoute: DashboardDashboardRouteRouteWithChildren,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
